minetest.register_on_newplayer(function(player)
	print("on_newplayer")
	if minetest.setting_getbool("insane") then
		print("giving give_initial_stuff to player")
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
		player:get_inventory():add_item('main', 'nuke:tnt 99')
	end
end)

