.\" Minetest man page
.TH minetest 6 "29 January 2012" "" ""

.SH NAME
minetest \- Multiplayer infinite-world block sandbox

.SH SYNOPSIS
.B minetest
[ OPTION ... ]

.SH DESCRIPTION
.B Minetest
is one of the first InfiniMiner/Minecraft(/whatever) inspired games (started October 2010), with a goal of taking the survival multiplayer gameplay to a slightly different direction.
.PP
The main design philosophy is to keep it technically simple, stable and portable. It will be kept lightweight enough to run on fairly old hardware.

.SH OPTIONS
.TP
\-\-address <value>
Address to connect to
.TP
\-\-config <value>
Load configuration from specified file
.TP
\-\-disable\-unittests
Disable unit tests
.TP
\-\-enable\-unittests
Enable unit tests
.TP
\-\-help
Show allowed options
.TP
\-\-info\-on\-stderr
Print debug information to console
.TP
\-\-map\-dir <value>
Map directory (where everything in the world is stored)
.TP
\-\-port <value>
Set network port to connect to
.TP
\-\-random\-input
Enable random user input, for testing
.TP
\-\-server
Run server directly
.TP
\-\-speedtests
Run speed tests

.SH BUGS
Please report all bugs to Perttu Ahola <celeron55@gmail.com>.

.SH AUTHOR
.PP
Perttu Ahola <celeron55@gmail.com>
and contributors.
.PP
This man page was written by
Juhani Numminen <juhaninumminen0@gmail.com>.

.SH WWW
http://c55.me/minetest/

.SH "SEE ALSO"
.BR minetestserver(6)