# Look for json, use our own if not found

#FIND_PATH(JSON_INCLUDE_DIR json.h)

#FIND_LIBRARY(JSON_LIBRARY NAMES json)

#IF(JSON_LIBRARY AND JSON_INCLUDE_DIR)
#	SET( JSON_FOUND TRUE )
#ENDIF(JSON_LIBRARY AND JSON_INCLUDE_DIR)

#IF(JSON_FOUND)
#	MESSAGE(STATUS "Found system json header file in ${JSON_INCLUDE_DIR}")
#	MESSAGE(STATUS "Found system json library ${JSON_LIBRARY}")
#ELSE(JSON_FOUND)
	SET(JSON_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/json)
	SET(JSON_LIBRARY json)
	MESSAGE(STATUS "Using project json library")
#ENDIF(JSON_FOUND)
