# Always run during 'make'

if(VERSION_EXTRA OR DISABLE_GIT_DETECTION)
	set(VERSION_GITHASH "${VERSION_STRING}")
else(VERSION_EXTRA OR DISABLE_GIT_DETECTION)
	execute_process(COMMAND git describe --always --tag --dirty
		WORKING_DIRECTORY "${GENERATE_VERSION_SOURCE_DIR}"
		OUTPUT_VARIABLE VERSION_GITHASH OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET)

	if(VERSION_GITHASH)
		message(STATUS "*** Detected git version ${VERSION_GITHASH} ***")
	else(VERSION_GITHASH)
		set(VERSION_GITHASH "${VERSION_STRING}")
	endif(VERSION_GITHASH)
endif(VERSION_EXTRA OR DISABLE_GIT_DETECTION)

configure_file(
	${GENERATE_VERSION_SOURCE_DIR}/cmake_config_githash.h.in
	${GENERATE_VERSION_BINARY_DIR}/cmake_config_githash.h)
