// This file is automatically generated

#include "settings_builtin.h"

static BuiltinSettings settings;
const BuiltinSettings &builtin_settings(settings);

// Enum settings
static SettingEnum<JoystickType> setting_joystick_type{&settings.joystick_type, {
	{JoystickType::Auto, "auto"},
	{JoystickType::Generic, "generic"},
	{JoystickType::Xbox, "xbox"},
}};

static SettingEnum<LeavesStyle> setting_leaves_style{&settings.leaves_style, {
	{LeavesStyle::Fancy, "fancy"},
	{LeavesStyle::Simple, "simple"},
	{LeavesStyle::Opaque, "opaque"},
}};

static SettingEnum<NodeHighlighting> setting_node_highlighting{&settings.node_highlighting, {
	{NodeHighlighting::Box, "box"},
	{NodeHighlighting::Halo, "halo"},
	{NodeHighlighting::None, "none"},
}};

static SettingInt setting_fsaa{&settings.fsaa, 0, 16};

static SettingInt setting_undersampling{&settings.undersampling, 0, 4};

static SettingEnum<VideoDriver> setting_video_driver{&settings.video_driver, {
	{VideoDriver::Null, "null"},
	{VideoDriver::Software, "software"},
	{VideoDriver::Burningsvideo, "burningsvideo"},
	{VideoDriver::Direct3d8, "direct3d8"},
	{VideoDriver::Direct3d9, "direct3d9"},
	{VideoDriver::Opengl, "opengl"},
	{VideoDriver::Ogles1, "ogles1"},
	{VideoDriver::Ogles2, "ogles2"},
}};

static SettingEnum<_3dMode> setting__3d_mode{&settings._3d_mode, {
	{_3dMode::None, "none"},
	{_3dMode::Anaglyph, "anaglyph"},
	{_3dMode::Interlaced, "interlaced"},
	{_3dMode::Topbottom, "topbottom"},
	{_3dMode::Sidebyside, "sidebyside"},
	{_3dMode::Pageflip, "pageflip"},
}};

static SettingEnum<WorldAlignedMode> setting_world_aligned_mode{&settings.world_aligned_mode, {
	{WorldAlignedMode::Disable, "disable"},
	{WorldAlignedMode::Enable, "enable"},
	{WorldAlignedMode::ForceSolid, "force_solid"},
	{WorldAlignedMode::ForceNodebox, "force_nodebox"},
}};

static SettingEnum<AutoscaleMode> setting_autoscale_mode{&settings.autoscale_mode, {
	{AutoscaleMode::Disable, "disable"},
	{AutoscaleMode::Enable, "enable"},
	{AutoscaleMode::Force, "force"},
}};

static SettingEnum<ScreenshotFormat> setting_screenshot_format{&settings.screenshot_format, {
	{ScreenshotFormat::Png, "png"},
	{ScreenshotFormat::Jpg, "jpg"},
	{ScreenshotFormat::Bmp, "bmp"},
	{ScreenshotFormat::Pcx, "pcx"},
	{ScreenshotFormat::Ppm, "ppm"},
	{ScreenshotFormat::Tga, "tga"},
}};

static SettingEnum<DeprecatedLuaApiHandling> setting_deprecated_lua_api_handling{&settings.deprecated_lua_api_handling, {
	{DeprecatedLuaApiHandling::Legacy, "legacy"},
	{DeprecatedLuaApiHandling::Log, "log"},
	{DeprecatedLuaApiHandling::Error, "error"},
}};

static SettingInt setting_sqlite_synchronous{&settings.sqlite_synchronous, 0, 2};

static SettingEnum<ProfilerDefaultReportFormat> setting_profiler_default_report_format{&settings.profiler_default_report_format, {
	{ProfilerDefaultReportFormat::Txt, "txt"},
	{ProfilerDefaultReportFormat::Csv, "csv"},
	{ProfilerDefaultReportFormat::Lua, "lua"},
	{ProfilerDefaultReportFormat::Json, "json"},
	{ProfilerDefaultReportFormat::JsonPretty, "json_pretty"},
}};

static SettingEnum<Language> setting_language{&settings.language, {
	{Language::_, ""},
	{Language::Be, "be"},
	{Language::Ca, "ca"},
	{Language::Cs, "cs"},
	{Language::Da, "da"},
	{Language::De, "de"},
	{Language::Dv, "dv"},
	{Language::En, "en"},
	{Language::Eo, "eo"},
	{Language::Es, "es"},
	{Language::Et, "et"},
	{Language::Fr, "fr"},
	{Language::He, "he"},
	{Language::Hu, "hu"},
	{Language::Id, "id"},
	{Language::It, "it"},
	{Language::Ja, "ja"},
	{Language::Jbo, "jbo"},
	{Language::Ko, "ko"},
	{Language::Ky, "ky"},
	{Language::Lt, "lt"},
	{Language::Ms, "ms"},
	{Language::Nb, "nb"},
	{Language::Nl, "nl"},
	{Language::Pl, "pl"},
	{Language::Pt, "pt"},
	{Language::PtBR, "pt_BR"},
	{Language::Ro, "ro"},
	{Language::Ru, "ru"},
	{Language::Sl, "sl"},
	{Language::SrCyrl, "sr_Cyrl"},
	{Language::Sv, "sv"},
	{Language::Sw, "sw"},
	{Language::Tr, "tr"},
	{Language::Uk, "uk"},
	{Language::ZhCN, "zh_CN"},
	{Language::ZhTW, "zh_TW"},
}};

static SettingEnum<DebugLogLevel> setting_debug_log_level{&settings.debug_log_level, {
	{DebugLogLevel::_, ""},
	{DebugLogLevel::None, "none"},
	{DebugLogLevel::Error, "error"},
	{DebugLogLevel::Warning, "warning"},
	{DebugLogLevel::Action, "action"},
	{DebugLogLevel::Info, "info"},
	{DebugLogLevel::Verbose, "verbose"},
}};

static SettingEnum<LogColor> setting_log_color{&settings.log_color, {
	{LogColor::Yes, "yes"},
	{LogColor::Detect, "detect"},
	{LogColor::No, "no"},
}};

static SettingEnum<MgName> setting_mg_name{&settings.mg_name, {
	{MgName::V5, "v5"},
	{MgName::V6, "v6"},
	{MgName::V7, "v7"},
	{MgName::Flat, "flat"},
	{MgName::Valleys, "valleys"},
	{MgName::Fractal, "fractal"},
	{MgName::Singlenode, "singlenode"},
}};


// Scalar settings
static SettingBool setting_enable_build_where_you_stand{&settings.enable_build_where_you_stand};
static SettingBool setting_free_move{&settings.free_move};
static SettingBool setting_fast_move{&settings.fast_move};
static SettingBool setting_noclip{&settings.noclip};
static SettingBool setting_cinematic{&settings.cinematic};
static SettingFloat setting_camera_smoothing{&settings.camera_smoothing, 0, 0.99};
static SettingFloat setting_cinematic_camera_smoothing{&settings.cinematic_camera_smoothing, 0, 0.99};
static SettingBool setting_invert_mouse{&settings.invert_mouse};
static SettingFloat setting_mouse_sensitivity{&settings.mouse_sensitivity};
static SettingBool setting_aux1_descends{&settings.aux1_descends};
static SettingBool setting_doubletap_jump{&settings.doubletap_jump};
static SettingBool setting_always_fly_fast{&settings.always_fly_fast};
static SettingFloat setting_repeat_rightclick_time{&settings.repeat_rightclick_time};
static SettingBool setting_safe_dig_and_place{&settings.safe_dig_and_place};
static SettingBool setting_random_input{&settings.random_input};
static SettingBool setting_continuous_forward{&settings.continuous_forward};
static SettingBool setting_enable_joysticks{&settings.enable_joysticks};
static SettingInt setting_joystick_id{&settings.joystick_id};
static SettingFloat setting_repeat_joystick_button_time{&settings.repeat_joystick_button_time};
static SettingFloat setting_joystick_frustum_sensitivity{&settings.joystick_frustum_sensitivity};
static SettingBool setting_enable_vbo{&settings.enable_vbo};
static SettingBool setting_enable_fog{&settings.enable_fog};
static SettingBool setting_connected_glass{&settings.connected_glass};
static SettingBool setting_smooth_lighting{&settings.smooth_lighting};
static SettingBool setting_enable_clouds{&settings.enable_clouds};
static SettingBool setting_enable_3d_clouds{&settings.enable_3d_clouds};
static SettingBool setting_enable_particles{&settings.enable_particles};
static SettingBool setting_mip_map{&settings.mip_map};
static SettingBool setting_anisotropic_filter{&settings.anisotropic_filter};
static SettingBool setting_bilinear_filter{&settings.bilinear_filter};
static SettingBool setting_trilinear_filter{&settings.trilinear_filter};
static SettingBool setting_texture_clean_transparent{&settings.texture_clean_transparent};
static SettingInt setting_texture_min_size{&settings.texture_min_size};
static SettingBool setting_enable_shaders{&settings.enable_shaders};
static SettingBool setting_tone_mapping{&settings.tone_mapping};
static SettingBool setting_enable_bumpmapping{&settings.enable_bumpmapping};
static SettingBool setting_generate_normalmaps{&settings.generate_normalmaps};
static SettingFloat setting_normalmaps_strength{&settings.normalmaps_strength};
static SettingInt setting_normalmaps_smooth{&settings.normalmaps_smooth, 0, 2};
static SettingBool setting_enable_parallax_occlusion{&settings.enable_parallax_occlusion};
static SettingInt setting_parallax_occlusion_mode{&settings.parallax_occlusion_mode, 0, 1};
static SettingFloat setting__3d_paralax_strength{&settings._3d_paralax_strength};
static SettingInt setting_parallax_occlusion_iterations{&settings.parallax_occlusion_iterations};
static SettingFloat setting_parallax_occlusion_scale{&settings.parallax_occlusion_scale};
static SettingFloat setting_parallax_occlusion_bias{&settings.parallax_occlusion_bias};
static SettingBool setting_enable_waving_water{&settings.enable_waving_water};
static SettingFloat setting_water_wave_height{&settings.water_wave_height};
static SettingFloat setting_water_wave_length{&settings.water_wave_length};
static SettingFloat setting_water_wave_speed{&settings.water_wave_speed};
static SettingBool setting_enable_waving_leaves{&settings.enable_waving_leaves};
static SettingBool setting_enable_waving_plants{&settings.enable_waving_plants};
static SettingBool setting_arm_inertia{&settings.arm_inertia};
static SettingInt setting_fps_max{&settings.fps_max};
static SettingInt setting_pause_fps_max{&settings.pause_fps_max};
static SettingBool setting_pause_on_lost_focus{&settings.pause_on_lost_focus};
static SettingInt setting_viewing_range{&settings.viewing_range, 20, 4000};
static SettingFloat setting_near_plane{&settings.near_plane, 0, 0.5};
static SettingInt setting_screen_w{&settings.screen_w};
static SettingInt setting_screen_h{&settings.screen_h};
static SettingBool setting_autosave_screensize{&settings.autosave_screensize};
static SettingBool setting_fullscreen{&settings.fullscreen};
static SettingInt setting_fullscreen_bpp{&settings.fullscreen_bpp};
static SettingBool setting_vsync{&settings.vsync};
static SettingInt setting_fov{&settings.fov, 30, 160};
static SettingFloat setting_display_gamma{&settings.display_gamma, 0.5, 3};
static SettingFloat setting_lighting_alpha{&settings.lighting_alpha, 0, 4};
static SettingFloat setting_lighting_beta{&settings.lighting_beta, 0, 4};
static SettingFloat setting_lighting_boost{&settings.lighting_boost, 0, 1};
static SettingFloat setting_lighting_boost_center{&settings.lighting_boost_center, 0, 1};
static SettingFloat setting_lighting_boost_spread{&settings.lighting_boost_spread, 0, 1};
static SettingInt setting_cloud_radius{&settings.cloud_radius};
static SettingFloat setting_view_bobbing_amount{&settings.view_bobbing_amount};
static SettingFloat setting_fall_bobbing_amount{&settings.fall_bobbing_amount};
static SettingFloat setting_console_height{&settings.console_height, 0.1, 1};
static SettingInt setting_console_alpha{&settings.console_alpha, 0, 255};
static SettingInt setting_formspec_fullscreen_bg_opacity{&settings.formspec_fullscreen_bg_opacity, 0, 255};
static SettingInt setting_formspec_default_bg_opacity{&settings.formspec_default_bg_opacity, 0, 255};
static SettingInt setting_selectionbox_width{&settings.selectionbox_width, 1, 5};
static SettingInt setting_crosshair_alpha{&settings.crosshair_alpha, 0, 255};
static SettingInt setting_recent_chat_messages{&settings.recent_chat_messages, 2, 20};
static SettingBool setting_desynchronize_mapblock_texture_animation{&settings.desynchronize_mapblock_texture_animation};
static SettingFloat setting_hud_hotbar_max_width{&settings.hud_hotbar_max_width};
static SettingFloat setting_hud_scaling{&settings.hud_scaling};
static SettingBool setting_enable_mesh_cache{&settings.enable_mesh_cache};
static SettingInt setting_mesh_generation_interval{&settings.mesh_generation_interval, 0, 50};
static SettingInt setting_meshgen_block_cache_size{&settings.meshgen_block_cache_size, 0, 1000};
static SettingBool setting_enable_minimap{&settings.enable_minimap};
static SettingBool setting_minimap_shape_round{&settings.minimap_shape_round};
static SettingBool setting_minimap_double_scan_height{&settings.minimap_double_scan_height};
static SettingBool setting_directional_colored_fog{&settings.directional_colored_fog};
static SettingFloat setting_ambient_occlusion_gamma{&settings.ambient_occlusion_gamma, 0.25, 4};
static SettingBool setting_inventory_items_animations{&settings.inventory_items_animations};
static SettingBool setting_inventory_image_hack{&settings.inventory_image_hack};
static SettingFloat setting_fog_start{&settings.fog_start, 0, 0.99};
static SettingBool setting_opaque_water{&settings.opaque_water};
static SettingBool setting_show_entity_selectionbox{&settings.show_entity_selectionbox};
static SettingBool setting_menu_clouds{&settings.menu_clouds};
static SettingFloat setting_gui_scaling{&settings.gui_scaling};
static SettingBool setting_gui_scaling_filter{&settings.gui_scaling_filter};
static SettingBool setting_gui_scaling_filter_txr2img{&settings.gui_scaling_filter_txr2img};
static SettingInt setting_tooltip_show_delay{&settings.tooltip_show_delay};
static SettingBool setting_tooltip_append_itemname{&settings.tooltip_append_itemname};
static SettingBool setting_freetype{&settings.freetype};
static SettingInt setting_font_size{&settings.font_size};
static SettingInt setting_font_shadow{&settings.font_shadow};
static SettingInt setting_font_shadow_alpha{&settings.font_shadow_alpha, 0, 255};
static SettingInt setting_mono_font_size{&settings.mono_font_size};
static SettingInt setting_fallback_font_size{&settings.fallback_font_size};
static SettingInt setting_fallback_font_shadow{&settings.fallback_font_shadow};
static SettingInt setting_fallback_font_shadow_alpha{&settings.fallback_font_shadow_alpha, 0, 255};
static SettingInt setting_screenshot_quality{&settings.screenshot_quality, 0, 100};
static SettingInt setting_screen_dpi{&settings.screen_dpi};
static SettingBool setting_enable_console{&settings.enable_console};
static SettingBool setting_enable_sound{&settings.enable_sound};
static SettingFloat setting_sound_volume{&settings.sound_volume, 0, 1};
static SettingBool setting_mute_sound{&settings.mute_sound};
static SettingInt setting_remote_port{&settings.remote_port, 1, 65535};
static SettingBool setting_enable_local_map_saving{&settings.enable_local_map_saving};
static SettingBool setting_enable_remote_media_server{&settings.enable_remote_media_server};
static SettingBool setting_enable_client_modding{&settings.enable_client_modding};
static SettingInt setting_max_out_chat_queue_size{&settings.max_out_chat_queue_size};
static SettingInt setting_client_unload_unused_data_timeout{&settings.client_unload_unused_data_timeout};
static SettingInt setting_client_mapblock_limit{&settings.client_mapblock_limit};
static SettingBool setting_show_debug{&settings.show_debug};
static SettingBool setting_server_announce{&settings.server_announce};
static SettingBool setting_strip_color_codes{&settings.strip_color_codes};
static SettingInt setting_port{&settings.port};
static SettingBool setting_strict_protocol_version_checking{&settings.strict_protocol_version_checking};
static SettingBool setting_ipv6_server{&settings.ipv6_server};
static SettingInt setting_max_simultaneous_block_sends_per_client{&settings.max_simultaneous_block_sends_per_client};
static SettingFloat setting_full_block_send_enable_min_time_from_building{&settings.full_block_send_enable_min_time_from_building};
static SettingInt setting_max_packets_per_iteration{&settings.max_packets_per_iteration};
static SettingInt setting_max_users{&settings.max_users};
static SettingInt setting_item_entity_ttl{&settings.item_entity_ttl};
static SettingBool setting_show_statusline_on_connect{&settings.show_statusline_on_connect};
static SettingBool setting_enable_damage{&settings.enable_damage};
static SettingBool setting_creative_mode{&settings.creative_mode};
static SettingBool setting_unlimited_player_transfer_distance{&settings.unlimited_player_transfer_distance};
static SettingInt setting_player_transfer_distance{&settings.player_transfer_distance};
static SettingBool setting_enable_pvp{&settings.enable_pvp};
static SettingBool setting_enable_mod_channels{&settings.enable_mod_channels};
static SettingBool setting_disallow_empty_password{&settings.disallow_empty_password};
static SettingBool setting_disable_anticheat{&settings.disable_anticheat};
static SettingBool setting_enable_rollback_recording{&settings.enable_rollback_recording};
static SettingBool setting_ask_reconnect_on_crash{&settings.ask_reconnect_on_crash};
static SettingInt setting_active_object_send_range_blocks{&settings.active_object_send_range_blocks};
static SettingInt setting_active_block_range{&settings.active_block_range};
static SettingInt setting_max_block_send_distance{&settings.max_block_send_distance};
static SettingInt setting_max_forceloaded_blocks{&settings.max_forceloaded_blocks};
static SettingInt setting_time_send_interval{&settings.time_send_interval};
static SettingInt setting_time_speed{&settings.time_speed};
static SettingInt setting_world_start_time{&settings.world_start_time, 0, 23999};
static SettingFloat setting_server_map_save_interval{&settings.server_map_save_interval};
static SettingFloat setting_movement_acceleration_default{&settings.movement_acceleration_default};
static SettingFloat setting_movement_acceleration_air{&settings.movement_acceleration_air};
static SettingFloat setting_movement_acceleration_fast{&settings.movement_acceleration_fast};
static SettingFloat setting_movement_speed_walk{&settings.movement_speed_walk};
static SettingFloat setting_movement_speed_crouch{&settings.movement_speed_crouch};
static SettingFloat setting_movement_speed_fast{&settings.movement_speed_fast};
static SettingFloat setting_movement_speed_climb{&settings.movement_speed_climb};
static SettingFloat setting_movement_speed_jump{&settings.movement_speed_jump};
static SettingFloat setting_movement_liquid_fluidity{&settings.movement_liquid_fluidity};
static SettingFloat setting_movement_liquid_fluidity_smooth{&settings.movement_liquid_fluidity_smooth};
static SettingFloat setting_movement_liquid_sink{&settings.movement_liquid_sink};
static SettingFloat setting_movement_gravity{&settings.movement_gravity};
static SettingInt setting_max_clearobjects_extra_loaded_blocks{&settings.max_clearobjects_extra_loaded_blocks};
static SettingInt setting_server_unload_unused_data_timeout{&settings.server_unload_unused_data_timeout};
static SettingInt setting_max_objects_per_block{&settings.max_objects_per_block};
static SettingFloat setting_dedicated_server_step{&settings.dedicated_server_step};
static SettingFloat setting_active_block_mgmt_interval{&settings.active_block_mgmt_interval};
static SettingFloat setting_abm_interval{&settings.abm_interval};
static SettingFloat setting_nodetimer_interval{&settings.nodetimer_interval};
static SettingBool setting_ignore_world_load_errors{&settings.ignore_world_load_errors};
static SettingInt setting_liquid_loop_max{&settings.liquid_loop_max};
static SettingInt setting_liquid_queue_purge_time{&settings.liquid_queue_purge_time};
static SettingFloat setting_liquid_update{&settings.liquid_update};
static SettingInt setting_block_send_optimize_distance{&settings.block_send_optimize_distance, 2};
static SettingBool setting_server_side_occlusion_culling{&settings.server_side_occlusion_culling};
static SettingInt setting_csm_flavour_limits{&settings.csm_flavour_limits};
static SettingInt setting_csm_flavour_noderange_limit{&settings.csm_flavour_noderange_limit};
static SettingBool setting_secure_enable_security{&settings.secure_enable_security};
static SettingBool setting_profiler_load{&settings.profiler_load};
static SettingBool setting_instrument_entity{&settings.instrument_entity};
static SettingBool setting_instrument_abm{&settings.instrument_abm};
static SettingBool setting_instrument_lbm{&settings.instrument_lbm};
static SettingBool setting_instrument_chatcommand{&settings.instrument_chatcommand};
static SettingBool setting_instrument_global_callback{&settings.instrument_global_callback};
static SettingBool setting_instrument_builtin{&settings.instrument_builtin};
static SettingBool setting_instrument_profiler{&settings.instrument_profiler};
static SettingBool setting_enable_ipv6{&settings.enable_ipv6};
static SettingInt setting_curl_timeout{&settings.curl_timeout};
static SettingInt setting_curl_parallel_limit{&settings.curl_parallel_limit};
static SettingInt setting_curl_file_download_timeout{&settings.curl_file_download_timeout};
static SettingBool setting_high_precision_fpu{&settings.high_precision_fpu};
static SettingInt setting_main_menu_game_mgr{&settings.main_menu_game_mgr};
static SettingInt setting_main_menu_mod_mgr{&settings.main_menu_mod_mgr};
static SettingInt setting_profiler_print_interval{&settings.profiler_print_interval};
static SettingInt setting_water_level{&settings.water_level};
static SettingInt setting_max_block_generate_distance{&settings.max_block_generate_distance};
static SettingInt setting_mapgen_limit{&settings.mapgen_limit, 0, 31000};
static SettingBool setting_projecting_dungeons{&settings.projecting_dungeons};
static SettingFloat setting_mgv5_cave_width{&settings.mgv5_cave_width};
static SettingInt setting_mgv5_large_cave_depth{&settings.mgv5_large_cave_depth};
static SettingInt setting_mgv5_lava_depth{&settings.mgv5_lava_depth};
static SettingInt setting_mgv5_cavern_limit{&settings.mgv5_cavern_limit};
static SettingInt setting_mgv5_cavern_taper{&settings.mgv5_cavern_taper};
static SettingFloat setting_mgv5_cavern_threshold{&settings.mgv5_cavern_threshold};
static SettingFloat setting_mgv6_freq_desert{&settings.mgv6_freq_desert};
static SettingFloat setting_mgv6_freq_beach{&settings.mgv6_freq_beach};
static SettingInt setting_mgv7_mount_zero_level{&settings.mgv7_mount_zero_level};
static SettingFloat setting_mgv7_cave_width{&settings.mgv7_cave_width};
static SettingInt setting_mgv7_large_cave_depth{&settings.mgv7_large_cave_depth};
static SettingInt setting_mgv7_lava_depth{&settings.mgv7_lava_depth};
static SettingFloat setting_mgv7_float_mount_density{&settings.mgv7_float_mount_density};
static SettingFloat setting_mgv7_float_mount_height{&settings.mgv7_float_mount_height};
static SettingFloat setting_mgv7_float_mount_exponent{&settings.mgv7_float_mount_exponent};
static SettingInt setting_mgv7_floatland_level{&settings.mgv7_floatland_level};
static SettingInt setting_mgv7_shadow_limit{&settings.mgv7_shadow_limit};
static SettingInt setting_mgv7_cavern_limit{&settings.mgv7_cavern_limit};
static SettingInt setting_mgv7_cavern_taper{&settings.mgv7_cavern_taper};
static SettingFloat setting_mgv7_cavern_threshold{&settings.mgv7_cavern_threshold};
static SettingFloat setting_mgcarpathian_cave_width{&settings.mgcarpathian_cave_width};
static SettingInt setting_mgcarpathian_large_cave_depth{&settings.mgcarpathian_large_cave_depth};
static SettingInt setting_mgcarpathian_lava_depth{&settings.mgcarpathian_lava_depth};
static SettingInt setting_mgcarpathian_cavern_limit{&settings.mgcarpathian_cavern_limit};
static SettingInt setting_mgcarpathian_cavern_taper{&settings.mgcarpathian_cavern_taper};
static SettingFloat setting_mgcarpathian_cavern_threshold{&settings.mgcarpathian_cavern_threshold};
static SettingInt setting_mgflat_ground_level{&settings.mgflat_ground_level};
static SettingInt setting_mgflat_large_cave_depth{&settings.mgflat_large_cave_depth};
static SettingInt setting_mgflat_lava_depth{&settings.mgflat_lava_depth};
static SettingFloat setting_mgflat_cave_width{&settings.mgflat_cave_width};
static SettingFloat setting_mgflat_lake_threshold{&settings.mgflat_lake_threshold};
static SettingFloat setting_mgflat_lake_steepness{&settings.mgflat_lake_steepness};
static SettingFloat setting_mgflat_hill_threshold{&settings.mgflat_hill_threshold};
static SettingFloat setting_mgflat_hill_steepness{&settings.mgflat_hill_steepness};
static SettingFloat setting_mgfractal_cave_width{&settings.mgfractal_cave_width};
static SettingInt setting_mgfractal_large_cave_depth{&settings.mgfractal_large_cave_depth};
static SettingInt setting_mgfractal_lava_depth{&settings.mgfractal_lava_depth};
static SettingInt setting_mgfractal_fractal{&settings.mgfractal_fractal, 1, 18};
static SettingInt setting_mgfractal_iterations{&settings.mgfractal_iterations};
static SettingFloat setting_mgfractal_slice_w{&settings.mgfractal_slice_w};
static SettingFloat setting_mgfractal_julia_x{&settings.mgfractal_julia_x};
static SettingFloat setting_mgfractal_julia_y{&settings.mgfractal_julia_y};
static SettingFloat setting_mgfractal_julia_z{&settings.mgfractal_julia_z};
static SettingFloat setting_mgfractal_julia_w{&settings.mgfractal_julia_w};
static SettingInt setting_mgvalleys_altitude_chill{&settings.mgvalleys_altitude_chill};
static SettingInt setting_mgvalleys_large_cave_depth{&settings.mgvalleys_large_cave_depth};
static SettingInt setting_mgvalleys_lava_features{&settings.mgvalleys_lava_features};
static SettingInt setting_mgvalleys_massive_cave_depth{&settings.mgvalleys_massive_cave_depth};
static SettingInt setting_mgvalleys_river_depth{&settings.mgvalleys_river_depth};
static SettingInt setting_mgvalleys_river_size{&settings.mgvalleys_river_size};
static SettingInt setting_mgvalleys_water_features{&settings.mgvalleys_water_features};
static SettingFloat setting_mgvalleys_cave_width{&settings.mgvalleys_cave_width};
static SettingInt setting_chunksize{&settings.chunksize};
static SettingBool setting_enable_mapgen_debug_info{&settings.enable_mapgen_debug_info};
static SettingInt setting_emergequeue_limit_total{&settings.emergequeue_limit_total};
static SettingInt setting_emergequeue_limit_diskonly{&settings.emergequeue_limit_diskonly};
static SettingInt setting_emergequeue_limit_generate{&settings.emergequeue_limit_generate};
static SettingInt setting_num_emerge_threads{&settings.num_emerge_threads};

// Map
static StaticSettingsManager::SettingTypes types{
	{"enable_build_where_you_stand", &setting_enable_build_where_you_stand},
	{"free_move", &setting_free_move},
	{"fast_move", &setting_fast_move},
	{"noclip", &setting_noclip},
	{"cinematic", &setting_cinematic},
	{"camera_smoothing", &setting_camera_smoothing},
	{"cinematic_camera_smoothing", &setting_cinematic_camera_smoothing},
	{"invert_mouse", &setting_invert_mouse},
	{"mouse_sensitivity", &setting_mouse_sensitivity},
	{"aux1_descends", &setting_aux1_descends},
	{"doubletap_jump", &setting_doubletap_jump},
	{"always_fly_fast", &setting_always_fly_fast},
	{"repeat_rightclick_time", &setting_repeat_rightclick_time},
	{"safe_dig_and_place", &setting_safe_dig_and_place},
	{"random_input", &setting_random_input},
	{"continuous_forward", &setting_continuous_forward},
	{"enable_joysticks", &setting_enable_joysticks},
	{"joystick_id", &setting_joystick_id},
	{"joystick_type", &setting_joystick_type},
	{"repeat_joystick_button_time", &setting_repeat_joystick_button_time},
	{"joystick_frustum_sensitivity", &setting_joystick_frustum_sensitivity},
	{"enable_vbo", &setting_enable_vbo},
	{"enable_fog", &setting_enable_fog},
	{"leaves_style", &setting_leaves_style},
	{"connected_glass", &setting_connected_glass},
	{"smooth_lighting", &setting_smooth_lighting},
	{"enable_clouds", &setting_enable_clouds},
	{"enable_3d_clouds", &setting_enable_3d_clouds},
	{"node_highlighting", &setting_node_highlighting},
	{"enable_particles", &setting_enable_particles},
	{"mip_map", &setting_mip_map},
	{"anisotropic_filter", &setting_anisotropic_filter},
	{"bilinear_filter", &setting_bilinear_filter},
	{"trilinear_filter", &setting_trilinear_filter},
	{"texture_clean_transparent", &setting_texture_clean_transparent},
	{"texture_min_size", &setting_texture_min_size},
	{"fsaa", &setting_fsaa},
	{"undersampling", &setting_undersampling},
	{"enable_shaders", &setting_enable_shaders},
	{"tone_mapping", &setting_tone_mapping},
	{"enable_bumpmapping", &setting_enable_bumpmapping},
	{"generate_normalmaps", &setting_generate_normalmaps},
	{"normalmaps_strength", &setting_normalmaps_strength},
	{"normalmaps_smooth", &setting_normalmaps_smooth},
	{"enable_parallax_occlusion", &setting_enable_parallax_occlusion},
	{"parallax_occlusion_mode", &setting_parallax_occlusion_mode},
	{"3d_paralax_strength", &setting__3d_paralax_strength},
	{"parallax_occlusion_iterations", &setting_parallax_occlusion_iterations},
	{"parallax_occlusion_scale", &setting_parallax_occlusion_scale},
	{"parallax_occlusion_bias", &setting_parallax_occlusion_bias},
	{"enable_waving_water", &setting_enable_waving_water},
	{"water_wave_height", &setting_water_wave_height},
	{"water_wave_length", &setting_water_wave_length},
	{"water_wave_speed", &setting_water_wave_speed},
	{"enable_waving_leaves", &setting_enable_waving_leaves},
	{"enable_waving_plants", &setting_enable_waving_plants},
	{"arm_inertia", &setting_arm_inertia},
	{"fps_max", &setting_fps_max},
	{"pause_fps_max", &setting_pause_fps_max},
	{"pause_on_lost_focus", &setting_pause_on_lost_focus},
	{"viewing_range", &setting_viewing_range},
	{"near_plane", &setting_near_plane},
	{"screen_w", &setting_screen_w},
	{"screen_h", &setting_screen_h},
	{"autosave_screensize", &setting_autosave_screensize},
	{"fullscreen", &setting_fullscreen},
	{"fullscreen_bpp", &setting_fullscreen_bpp},
	{"vsync", &setting_vsync},
	{"fov", &setting_fov},
	{"display_gamma", &setting_display_gamma},
	{"lighting_alpha", &setting_lighting_alpha},
	{"lighting_beta", &setting_lighting_beta},
	{"lighting_boost", &setting_lighting_boost},
	{"lighting_boost_center", &setting_lighting_boost_center},
	{"lighting_boost_spread", &setting_lighting_boost_spread},
	{"video_driver", &setting_video_driver},
	{"cloud_radius", &setting_cloud_radius},
	{"view_bobbing_amount", &setting_view_bobbing_amount},
	{"fall_bobbing_amount", &setting_fall_bobbing_amount},
	{"3d_mode", &setting__3d_mode},
	{"console_height", &setting_console_height},
	{"console_alpha", &setting_console_alpha},
	{"formspec_fullscreen_bg_opacity", &setting_formspec_fullscreen_bg_opacity},
	{"formspec_default_bg_opacity", &setting_formspec_default_bg_opacity},
	{"selectionbox_width", &setting_selectionbox_width},
	{"crosshair_alpha", &setting_crosshair_alpha},
	{"recent_chat_messages", &setting_recent_chat_messages},
	{"desynchronize_mapblock_texture_animation", &setting_desynchronize_mapblock_texture_animation},
	{"hud_hotbar_max_width", &setting_hud_hotbar_max_width},
	{"hud_scaling", &setting_hud_scaling},
	{"enable_mesh_cache", &setting_enable_mesh_cache},
	{"mesh_generation_interval", &setting_mesh_generation_interval},
	{"meshgen_block_cache_size", &setting_meshgen_block_cache_size},
	{"enable_minimap", &setting_enable_minimap},
	{"minimap_shape_round", &setting_minimap_shape_round},
	{"minimap_double_scan_height", &setting_minimap_double_scan_height},
	{"directional_colored_fog", &setting_directional_colored_fog},
	{"ambient_occlusion_gamma", &setting_ambient_occlusion_gamma},
	{"inventory_items_animations", &setting_inventory_items_animations},
	{"inventory_image_hack", &setting_inventory_image_hack},
	{"fog_start", &setting_fog_start},
	{"opaque_water", &setting_opaque_water},
	{"world_aligned_mode", &setting_world_aligned_mode},
	{"autoscale_mode", &setting_autoscale_mode},
	{"show_entity_selectionbox", &setting_show_entity_selectionbox},
	{"menu_clouds", &setting_menu_clouds},
	{"gui_scaling", &setting_gui_scaling},
	{"gui_scaling_filter", &setting_gui_scaling_filter},
	{"gui_scaling_filter_txr2img", &setting_gui_scaling_filter_txr2img},
	{"tooltip_show_delay", &setting_tooltip_show_delay},
	{"tooltip_append_itemname", &setting_tooltip_append_itemname},
	{"freetype", &setting_freetype},
	{"font_size", &setting_font_size},
	{"font_shadow", &setting_font_shadow},
	{"font_shadow_alpha", &setting_font_shadow_alpha},
	{"mono_font_size", &setting_mono_font_size},
	{"fallback_font_size", &setting_fallback_font_size},
	{"fallback_font_shadow", &setting_fallback_font_shadow},
	{"fallback_font_shadow_alpha", &setting_fallback_font_shadow_alpha},
	{"screenshot_format", &setting_screenshot_format},
	{"screenshot_quality", &setting_screenshot_quality},
	{"screen_dpi", &setting_screen_dpi},
	{"enable_console", &setting_enable_console},
	{"enable_sound", &setting_enable_sound},
	{"sound_volume", &setting_sound_volume},
	{"mute_sound", &setting_mute_sound},
	{"remote_port", &setting_remote_port},
	{"enable_local_map_saving", &setting_enable_local_map_saving},
	{"enable_remote_media_server", &setting_enable_remote_media_server},
	{"enable_client_modding", &setting_enable_client_modding},
	{"max_out_chat_queue_size", &setting_max_out_chat_queue_size},
	{"client_unload_unused_data_timeout", &setting_client_unload_unused_data_timeout},
	{"client_mapblock_limit", &setting_client_mapblock_limit},
	{"show_debug", &setting_show_debug},
	{"server_announce", &setting_server_announce},
	{"strip_color_codes", &setting_strip_color_codes},
	{"port", &setting_port},
	{"strict_protocol_version_checking", &setting_strict_protocol_version_checking},
	{"ipv6_server", &setting_ipv6_server},
	{"max_simultaneous_block_sends_per_client", &setting_max_simultaneous_block_sends_per_client},
	{"full_block_send_enable_min_time_from_building", &setting_full_block_send_enable_min_time_from_building},
	{"max_packets_per_iteration", &setting_max_packets_per_iteration},
	{"max_users", &setting_max_users},
	{"item_entity_ttl", &setting_item_entity_ttl},
	{"show_statusline_on_connect", &setting_show_statusline_on_connect},
	{"enable_damage", &setting_enable_damage},
	{"creative_mode", &setting_creative_mode},
	{"unlimited_player_transfer_distance", &setting_unlimited_player_transfer_distance},
	{"player_transfer_distance", &setting_player_transfer_distance},
	{"enable_pvp", &setting_enable_pvp},
	{"enable_mod_channels", &setting_enable_mod_channels},
	{"disallow_empty_password", &setting_disallow_empty_password},
	{"disable_anticheat", &setting_disable_anticheat},
	{"enable_rollback_recording", &setting_enable_rollback_recording},
	{"ask_reconnect_on_crash", &setting_ask_reconnect_on_crash},
	{"active_object_send_range_blocks", &setting_active_object_send_range_blocks},
	{"active_block_range", &setting_active_block_range},
	{"max_block_send_distance", &setting_max_block_send_distance},
	{"max_forceloaded_blocks", &setting_max_forceloaded_blocks},
	{"time_send_interval", &setting_time_send_interval},
	{"time_speed", &setting_time_speed},
	{"world_start_time", &setting_world_start_time},
	{"server_map_save_interval", &setting_server_map_save_interval},
	{"movement_acceleration_default", &setting_movement_acceleration_default},
	{"movement_acceleration_air", &setting_movement_acceleration_air},
	{"movement_acceleration_fast", &setting_movement_acceleration_fast},
	{"movement_speed_walk", &setting_movement_speed_walk},
	{"movement_speed_crouch", &setting_movement_speed_crouch},
	{"movement_speed_fast", &setting_movement_speed_fast},
	{"movement_speed_climb", &setting_movement_speed_climb},
	{"movement_speed_jump", &setting_movement_speed_jump},
	{"movement_liquid_fluidity", &setting_movement_liquid_fluidity},
	{"movement_liquid_fluidity_smooth", &setting_movement_liquid_fluidity_smooth},
	{"movement_liquid_sink", &setting_movement_liquid_sink},
	{"movement_gravity", &setting_movement_gravity},
	{"deprecated_lua_api_handling", &setting_deprecated_lua_api_handling},
	{"max_clearobjects_extra_loaded_blocks", &setting_max_clearobjects_extra_loaded_blocks},
	{"server_unload_unused_data_timeout", &setting_server_unload_unused_data_timeout},
	{"max_objects_per_block", &setting_max_objects_per_block},
	{"sqlite_synchronous", &setting_sqlite_synchronous},
	{"dedicated_server_step", &setting_dedicated_server_step},
	{"active_block_mgmt_interval", &setting_active_block_mgmt_interval},
	{"abm_interval", &setting_abm_interval},
	{"nodetimer_interval", &setting_nodetimer_interval},
	{"ignore_world_load_errors", &setting_ignore_world_load_errors},
	{"liquid_loop_max", &setting_liquid_loop_max},
	{"liquid_queue_purge_time", &setting_liquid_queue_purge_time},
	{"liquid_update", &setting_liquid_update},
	{"block_send_optimize_distance", &setting_block_send_optimize_distance},
	{"server_side_occlusion_culling", &setting_server_side_occlusion_culling},
	{"csm_flavour_limits", &setting_csm_flavour_limits},
	{"csm_flavour_noderange_limit", &setting_csm_flavour_noderange_limit},
	{"secure.enable_security", &setting_secure_enable_security},
	{"profiler.load", &setting_profiler_load},
	{"profiler.default_report_format", &setting_profiler_default_report_format},
	{"instrument.entity", &setting_instrument_entity},
	{"instrument.abm", &setting_instrument_abm},
	{"instrument.lbm", &setting_instrument_lbm},
	{"instrument.chatcommand", &setting_instrument_chatcommand},
	{"instrument.global_callback", &setting_instrument_global_callback},
	{"instrument.builtin", &setting_instrument_builtin},
	{"instrument.profiler", &setting_instrument_profiler},
	{"language", &setting_language},
	{"debug_log_level", &setting_debug_log_level},
	{"log_color", &setting_log_color},
	{"enable_ipv6", &setting_enable_ipv6},
	{"curl_timeout", &setting_curl_timeout},
	{"curl_parallel_limit", &setting_curl_parallel_limit},
	{"curl_file_download_timeout", &setting_curl_file_download_timeout},
	{"high_precision_fpu", &setting_high_precision_fpu},
	{"main_menu_game_mgr", &setting_main_menu_game_mgr},
	{"main_menu_mod_mgr", &setting_main_menu_mod_mgr},
	{"profiler_print_interval", &setting_profiler_print_interval},
	{"mg_name", &setting_mg_name},
	{"water_level", &setting_water_level},
	{"max_block_generate_distance", &setting_max_block_generate_distance},
	{"mapgen_limit", &setting_mapgen_limit},
	{"projecting_dungeons", &setting_projecting_dungeons},
	{"mgv5_cave_width", &setting_mgv5_cave_width},
	{"mgv5_large_cave_depth", &setting_mgv5_large_cave_depth},
	{"mgv5_lava_depth", &setting_mgv5_lava_depth},
	{"mgv5_cavern_limit", &setting_mgv5_cavern_limit},
	{"mgv5_cavern_taper", &setting_mgv5_cavern_taper},
	{"mgv5_cavern_threshold", &setting_mgv5_cavern_threshold},
	{"mgv6_freq_desert", &setting_mgv6_freq_desert},
	{"mgv6_freq_beach", &setting_mgv6_freq_beach},
	{"mgv7_mount_zero_level", &setting_mgv7_mount_zero_level},
	{"mgv7_cave_width", &setting_mgv7_cave_width},
	{"mgv7_large_cave_depth", &setting_mgv7_large_cave_depth},
	{"mgv7_lava_depth", &setting_mgv7_lava_depth},
	{"mgv7_float_mount_density", &setting_mgv7_float_mount_density},
	{"mgv7_float_mount_height", &setting_mgv7_float_mount_height},
	{"mgv7_float_mount_exponent", &setting_mgv7_float_mount_exponent},
	{"mgv7_floatland_level", &setting_mgv7_floatland_level},
	{"mgv7_shadow_limit", &setting_mgv7_shadow_limit},
	{"mgv7_cavern_limit", &setting_mgv7_cavern_limit},
	{"mgv7_cavern_taper", &setting_mgv7_cavern_taper},
	{"mgv7_cavern_threshold", &setting_mgv7_cavern_threshold},
	{"mgcarpathian_cave_width", &setting_mgcarpathian_cave_width},
	{"mgcarpathian_large_cave_depth", &setting_mgcarpathian_large_cave_depth},
	{"mgcarpathian_lava_depth", &setting_mgcarpathian_lava_depth},
	{"mgcarpathian_cavern_limit", &setting_mgcarpathian_cavern_limit},
	{"mgcarpathian_cavern_taper", &setting_mgcarpathian_cavern_taper},
	{"mgcarpathian_cavern_threshold", &setting_mgcarpathian_cavern_threshold},
	{"mgflat_ground_level", &setting_mgflat_ground_level},
	{"mgflat_large_cave_depth", &setting_mgflat_large_cave_depth},
	{"mgflat_lava_depth", &setting_mgflat_lava_depth},
	{"mgflat_cave_width", &setting_mgflat_cave_width},
	{"mgflat_lake_threshold", &setting_mgflat_lake_threshold},
	{"mgflat_lake_steepness", &setting_mgflat_lake_steepness},
	{"mgflat_hill_threshold", &setting_mgflat_hill_threshold},
	{"mgflat_hill_steepness", &setting_mgflat_hill_steepness},
	{"mgfractal_cave_width", &setting_mgfractal_cave_width},
	{"mgfractal_large_cave_depth", &setting_mgfractal_large_cave_depth},
	{"mgfractal_lava_depth", &setting_mgfractal_lava_depth},
	{"mgfractal_fractal", &setting_mgfractal_fractal},
	{"mgfractal_iterations", &setting_mgfractal_iterations},
	{"mgfractal_slice_w", &setting_mgfractal_slice_w},
	{"mgfractal_julia_x", &setting_mgfractal_julia_x},
	{"mgfractal_julia_y", &setting_mgfractal_julia_y},
	{"mgfractal_julia_z", &setting_mgfractal_julia_z},
	{"mgfractal_julia_w", &setting_mgfractal_julia_w},
	{"mgvalleys_altitude_chill", &setting_mgvalleys_altitude_chill},
	{"mgvalleys_large_cave_depth", &setting_mgvalleys_large_cave_depth},
	{"mgvalleys_lava_features", &setting_mgvalleys_lava_features},
	{"mgvalleys_massive_cave_depth", &setting_mgvalleys_massive_cave_depth},
	{"mgvalleys_river_depth", &setting_mgvalleys_river_depth},
	{"mgvalleys_river_size", &setting_mgvalleys_river_size},
	{"mgvalleys_water_features", &setting_mgvalleys_water_features},
	{"mgvalleys_cave_width", &setting_mgvalleys_cave_width},
	{"chunksize", &setting_chunksize},
	{"enable_mapgen_debug_info", &setting_enable_mapgen_debug_info},
	{"emergequeue_limit_total", &setting_emergequeue_limit_total},
	{"emergequeue_limit_diskonly", &setting_emergequeue_limit_diskonly},
	{"emergequeue_limit_generate", &setting_emergequeue_limit_generate},
	{"num_emerge_threads", &setting_num_emerge_threads},
};

StaticSettingsManager builtin_settings_manager(types);
