/*
Minetest
Copyright (C) 2010-2015 celeron55, Perttu Ahola <celeron55@gmail.com>

This program is free software you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation either version 2.1 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along
with this program if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/* This is no regular include header with guards and such, it is used to
 * generate settings related code.
 * The defaults aren't final, check defaultsettings.cpp for the adjustment it does.
 * If you include this file, you have to define a macro
 * MTCONF_SET_EXT(enum name, official name, default value), where
 * "official name" is used as string specifier for the name.
 * For the sake of better error reporting when a subsequent usage of this file is wrong,
 * you should undef that value again after inclusion.
 * If you evaluate default or lowercase values, this file relies on util/string.h and
 * config.h. If you don't evaluate those, it solely relies on config.h.
 * You have to ensure the needed files when you include this file.
 */

#ifndef MTCONF_SET_EXT
	#error "MTCONF_SET_EXT needs to be set when including settingdef.h!"
#else
	#define MTCONF_SET_SIMPLE(uppercase, default) MTCONF_SET_EXT(uppercase, lowercase( #uppercase ), default)
#endif

// Client and server

MTCONF_SET_SIMPLE(NAME, "")

// Client stuff
MTCONF_SET_SIMPLE(REMOTE_PORT, "30000")
MTCONF_SET_SIMPLE(KEYMAP_FORWARD, "KEY_KEY_W")
MTCONF_SET_SIMPLE(KEYMAP_BACKWARD, "KEY_KEY_S")
MTCONF_SET_SIMPLE(KEYMAP_LEFT, "KEY_KEY_A")
MTCONF_SET_SIMPLE(KEYMAP_RIGHT, "KEY_KEY_D")
MTCONF_SET_SIMPLE(KEYMAP_JUMP, "KEY_SPACE")
MTCONF_SET_SIMPLE(KEYMAP_SNEAK, "KEY_LSHIFT")
MTCONF_SET_SIMPLE(KEYMAP_DROP, "KEY_KEY_Q")
MTCONF_SET_SIMPLE(KEYMAP_INVENTORY, "KEY_KEY_I")
MTCONF_SET_SIMPLE(KEYMAP_SPECIAL1, "KEY_KEY_E")
MTCONF_SET_SIMPLE(KEYMAP_CHAT, "KEY_KEY_T")
MTCONF_SET_SIMPLE(KEYMAP_CMD, "/")
MTCONF_SET_SIMPLE(KEYMAP_CONSOLE, "KEY_F10")
MTCONF_SET_SIMPLE(KEYMAP_RANGESELECT, "KEY_KEY_R")
MTCONF_SET_SIMPLE(KEYMAP_FREEMOVE, "KEY_KEY_K")
MTCONF_SET_SIMPLE(KEYMAP_FASTMOVE, "KEY_KEY_J")
MTCONF_SET_SIMPLE(KEYMAP_NOCLIP, "KEY_KEY_H")
MTCONF_SET_SIMPLE(KEYMAP_CINEMATIC, "KEY_F8")
MTCONF_SET_SIMPLE(KEYMAP_SCREENSHOT, "KEY_F12")
MTCONF_SET_SIMPLE(KEYMAP_TOGGLE_HUD, "KEY_F1")
MTCONF_SET_SIMPLE(KEYMAP_TOGGLE_CHAT, "KEY_F2")
MTCONF_SET_SIMPLE(KEYMAP_TOGGLE_FORCE_FOG_OFF, "KEY_F3")
#if DEBUG
MTCONF_SET_SIMPLE(KEYMAP_TOGGLE_UPDATE_CAMERA, "KEY_F4")
#else
MTCONF_SET_SIMPLE(KEYMAP_TOGGLE_UPDATE_CAMERA, "none")
#endif
MTCONF_SET_SIMPLE(KEYMAP_TOGGLE_DEBUG, "KEY_F5")
MTCONF_SET_SIMPLE(KEYMAP_TOGGLE_PROFILER, "KEY_F6")
MTCONF_SET_SIMPLE(KEYMAP_CAMERA_MODE, "KEY_F7")
MTCONF_SET_SIMPLE(KEYMAP_INCREASE_VIEWING_RANGE_MIN, "+")
MTCONF_SET_SIMPLE(KEYMAP_DECREASE_VIEWING_RANGE_MIN, "-")
MTCONF_SET_SIMPLE(ENABLE_BUILD_WHERE_YOU_STAND, "false")
MTCONF_SET_SIMPLE(3D_MODE, "none")
MTCONF_SET_SIMPLE(3D_PARALAX_STRENGTH, "0.025")
MTCONF_SET_SIMPLE(AUX1_DESCENDS, "false")
MTCONF_SET_SIMPLE(DOUBLETAP_JUMP, "false")
MTCONF_SET_SIMPLE(ALWAYS_FLY_FAST, "true")
MTCONF_SET_SIMPLE(DIRECTIONAL_COLORED_FOG, "true")
MTCONF_SET_SIMPLE(TOOLTIP_SHOW_DELAY, "400")

// Some (temporary) keys for debugging
MTCONF_SET_SIMPLE(KEYMAP_PRINT_DEBUG_STACKS, "KEY_KEY_P")
MTCONF_SET_SIMPLE(KEYMAP_QUICKTUNE_PREV, "KEY_HOME")
MTCONF_SET_SIMPLE(KEYMAP_QUICKTUNE_NEXT, "KEY_END")
MTCONF_SET_SIMPLE(KEYMAP_QUICKTUNE_DEC, "KEY_NEXT")
MTCONF_SET_SIMPLE(KEYMAP_QUICKTUNE_INC, "KEY_PRIOR")

// Show debug info by default?
#ifdef NDEBUG
MTCONF_SET_SIMPLE(SHOW_DEBUG, "false")
#else
MTCONF_SET_SIMPLE(SHOW_DEBUG, "true")
#endif

MTCONF_SET_SIMPLE(WANTED_FPS, "30")
MTCONF_SET_SIMPLE(FPS_MAX, "60")
MTCONF_SET_SIMPLE(PAUSE_FPS_MAX, "20")
// A bit more than the server will send around the player, to make fog blend well
MTCONF_SET_SIMPLE(VIEWING_RANGE_NODES_MAX, "240")
MTCONF_SET_SIMPLE(VIEWING_RANGE_NODES_MIN, "35")
MTCONF_SET_EXT(SCREENW, "screenW", "800")
MTCONF_SET_EXT(SCREENH, "screenH", "600")
MTCONF_SET_SIMPLE(FULLSCREEN, "false")
MTCONF_SET_SIMPLE(FULLSCREEN_BPP, "24")
MTCONF_SET_SIMPLE(FSAA, "0")
MTCONF_SET_SIMPLE(VSYNC, "false")
MTCONF_SET_SIMPLE(ADDRESS, "")
MTCONF_SET_SIMPLE(RANDOM_INPUT, "false")
MTCONF_SET_SIMPLE(CLIENT_UNLOAD_UNUSED_DATA_TIMEOUT, "600")
MTCONF_SET_SIMPLE(ENABLE_FOG, "true")
MTCONF_SET_SIMPLE(FOV, "72")
MTCONF_SET_SIMPLE(VIEW_BOBBING, "true")
MTCONF_SET_SIMPLE(NEW_STYLE_WATER, "false")
MTCONF_SET_SIMPLE(NEW_STYLE_LEAVES, "true")
MTCONF_SET_SIMPLE(CONNECTED_GLASS, "false")
MTCONF_SET_SIMPLE(SMOOTH_LIGHTING, "true")
MTCONF_SET_SIMPLE(DISPLAY_GAMMA, "1.8")
MTCONF_SET_SIMPLE(TEXTURE_PATH, "")
MTCONF_SET_SIMPLE(SHADER_PATH, "")
MTCONF_SET_SIMPLE(VIDEO_DRIVER, "opengl")
MTCONF_SET_SIMPLE(FREE_MOVE, "false")
MTCONF_SET_SIMPLE(NOCLIP, "false")
MTCONF_SET_SIMPLE(CONTINUOUS_FORWARD, "false")
MTCONF_SET_SIMPLE(CINEMATIC, "false")
MTCONF_SET_SIMPLE(CAMERA_SMOOTHING, "0")
MTCONF_SET_SIMPLE(CINEMATIC_CAMERA_SMOOTHING, "0.7")
MTCONF_SET_SIMPLE(FAST_MOVE, "false")
MTCONF_SET_SIMPLE(INVERT_MOUSE, "false")
MTCONF_SET_SIMPLE(ENABLE_CLOUDS, "true")
MTCONF_SET_SIMPLE(SCREENSHOT_PATH, ".")
MTCONF_SET_SIMPLE(VIEW_BOBBING_AMOUNT, "1.0")
MTCONF_SET_SIMPLE(FALL_BOBBING_AMOUNT, "0.0")
MTCONF_SET_SIMPLE(ENABLE_3D_CLOUDS, "true")
MTCONF_SET_SIMPLE(CLOUD_HEIGHT, "120")
MTCONF_SET_SIMPLE(CLOUD_RADIUS, "12")
MTCONF_SET_SIMPLE(MENU_CLOUDS, "true")
MTCONF_SET_SIMPLE(OPAQUE_WATER, "false")
MTCONF_SET_SIMPLE(CONSOLE_COLOR, "")
MTCONF_SET_SIMPLE(CONSOLE_ALPHA, "200")
MTCONF_SET_SIMPLE(SELECTIONBOX_COLOR, "")
MTCONF_SET_SIMPLE(ENABLE_NODE_HIGHLIGHTING, "false")
MTCONF_SET_SIMPLE(CROSSHAIR_COLOR, "")
MTCONF_SET_SIMPLE(CROSSHAIR_ALPHA, "255")
MTCONF_SET_SIMPLE(HUD_SCALING, "1.0")
MTCONF_SET_SIMPLE(GUI_SCALING, "1.0")
MTCONF_SET_SIMPLE(GUI_SCALING_FILTER, "false")
MTCONF_SET_SIMPLE(GUI_SCALING_FILTER_TXR2IMG, "true")
MTCONF_SET_SIMPLE(MOUSE_SENSITIVITY, "0.2")
MTCONF_SET_SIMPLE(ENABLE_SOUND, "true")
MTCONF_SET_SIMPLE(SOUND_VOLUME, "0.8")
MTCONF_SET_SIMPLE(DESYNCHRONIZE_MAPBLOCK_TEXTURE_ANIMATION, "true")
MTCONF_SET_SIMPLE(SELECTIONBOX_WIDTH, "2")
MTCONF_SET_SIMPLE(HUD_HOTBAR_MAX_WIDTH, "1.0")
MTCONF_SET_SIMPLE(ENABLE_LOCAL_MAP_SAVING, "false")

MTCONF_SET_SIMPLE(MIP_MAP, "false")
MTCONF_SET_SIMPLE(ANISOTROPIC_FILTER, "false")
MTCONF_SET_SIMPLE(BILINEAR_FILTER, "false")
MTCONF_SET_SIMPLE(TRILINEAR_FILTER, "false")
MTCONF_SET_SIMPLE(TEXTURE_CLEAN_TRANSPARENT, "false")
MTCONF_SET_SIMPLE(TEXTURE_MIN_SIZE, "64")
MTCONF_SET_SIMPLE(PRELOAD_ITEM_VISUALS, "false")
MTCONF_SET_SIMPLE(ENABLE_BUMPMAPPING, "false")
MTCONF_SET_SIMPLE(ENABLE_PARALLAX_OCCLUSION, "false")
MTCONF_SET_SIMPLE(GENERATE_NORMALMAPS, "false")
MTCONF_SET_SIMPLE(NORMALMAPS_STRENGTH, "0.6")
MTCONF_SET_SIMPLE(NORMALMAPS_SMOOTH, "1")
MTCONF_SET_SIMPLE(PARALLAX_OCCLUSION_SCALE, "0.06")
MTCONF_SET_SIMPLE(PARALLAX_OCCLUSION_BIAS, "0.03")
MTCONF_SET_SIMPLE(ENABLE_WAVING_WATER, "false")
MTCONF_SET_SIMPLE(WATER_WAVE_HEIGHT, "1.0")
MTCONF_SET_SIMPLE(WATER_WAVE_LENGTH, "20.0")
MTCONF_SET_SIMPLE(WATER_WAVE_SPEED, "5.0")
MTCONF_SET_SIMPLE(ENABLE_WAVING_LEAVES, "false")
MTCONF_SET_SIMPLE(ENABLE_WAVING_PLANTS, "false")
MTCONF_SET_SIMPLE(AMBIENT_OCCLUSION_GAMMA, "2.2")
MTCONF_SET_SIMPLE(ENABLE_SHADERS, "true")
MTCONF_SET_SIMPLE(REPEAT_RIGHTCLICK_TIME, "0.25")
MTCONF_SET_SIMPLE(ENABLE_PARTICLES, "true")
MTCONF_SET_SIMPLE(ENABLE_MESH_CACHE, "true")

MTCONF_SET_SIMPLE(CURL_TIMEOUT, "5000")
MTCONF_SET_SIMPLE(CURL_PARALLEL_LIMIT, "8")
MTCONF_SET_SIMPLE(CURL_FILE_DOWNLOAD_TIMEOUT, "300000")
MTCONF_SET_SIMPLE(CURL_VERIFY_CERT, "true")

MTCONF_SET_SIMPLE(ENABLE_REMOTE_MEDIA_SERVER, "true")

MTCONF_SET_SIMPLE(SERVERLIST_URL, "servers.minetest.net")
MTCONF_SET_SIMPLE(SERVERLIST_FILE, "favoriteservers.txt")
MTCONF_SET_SIMPLE(SERVER_ANNOUNCE, "false")
MTCONF_SET_SIMPLE(SERVER_URL, "")
MTCONF_SET_SIMPLE(SERVER_ADDRESS, "")
MTCONF_SET_SIMPLE(SERVER_NAME, "")
MTCONF_SET_SIMPLE(SERVER_DESCRIPTION, "")

#if USE_FREETYPE
MTCONF_SET_SIMPLE(FREETYPE, "true")
MTCONF_SET_SIMPLE(FONT_PATH, porting::getDataPath("fonts" DIR_DELIM "liberationsans.ttf"))
MTCONF_SET_SIMPLE(FONT_SHADOW, "1")
MTCONF_SET_SIMPLE(FONT_SHADOW_ALPHA, "128")
MTCONF_SET_SIMPLE(MONO_FONT_PATH, porting::getDataPath("fonts" DIR_DELIM "liberationmono.ttf"))
MTCONF_SET_SIMPLE(FALLBACK_FONT_PATH, porting::getDataPath("fonts" DIR_DELIM "DroidSansFallbackFull.ttf"))

MTCONF_SET_SIMPLE(FALLBACK_FONT_SHADOW, "1")
MTCONF_SET_SIMPLE(FALLBACK_FONT_SHADOW_ALPHA, "128")

MTCONF_SET_SIMPLE(FONT_SIZE, itos(TTF_DEFAULT_FONT_SIZE))
MTCONF_SET_SIMPLE(MONO_FONT_SIZE, itos(TTF_DEFAULT_FONT_SIZE))
MTCONF_SET_SIMPLE(FALLBACK_FONT_SIZE, itos(TTF_DEFAULT_FONT_SIZE))
#else
MTCONF_SET_SIMPLE(FREETYPE, "false")
MTCONF_SET_SIMPLE(FONT_PATH, porting::getDataPath("fonts" DIR_DELIM "lucida_sans"))
MTCONF_SET_SIMPLE(MONO_FONT_PATH, porting::getDataPath("fonts" DIR_DELIM "mono_dejavu_sans"))

MTCONF_SET_SIMPLE(FONT_SIZE, itos(DEFAULT_FONT_SIZE))
MTCONF_SET_SIMPLE(MONO_FONT_SIZE, itos(DEFAULT_FONT_SIZE))
#endif

// Server stuff
// "map-dir" doesn't exist by default.
MTCONF_SET_SIMPLE(WORKAROUND_WINDOW_SIZE, "5")
MTCONF_SET_SIMPLE(MAX_PACKETS_PER_ITERATION, "1024")
MTCONF_SET_SIMPLE(PORT, "30000")
MTCONF_SET_SIMPLE(BIND_ADDRESS, "")
MTCONF_SET_SIMPLE(DEFAULT_GAME, "minetest")
MTCONF_SET_SIMPLE(MOTD, "")
MTCONF_SET_SIMPLE(MAX_USERS, "15")
MTCONF_SET_SIMPLE(STRICT_PROTOCOL_VERSION_CHECKING, "false")
MTCONF_SET_SIMPLE(CREATIVE_MODE, "false")
MTCONF_SET_SIMPLE(ENABLE_DAMAGE, "true")
MTCONF_SET_SIMPLE(FIXED_MAP_SEED, "")
MTCONF_SET_SIMPLE(GIVE_INITIAL_STUFF, "false")
MTCONF_SET_SIMPLE(DEFAULT_PASSWORD, "")
MTCONF_SET_SIMPLE(DEFAULT_PRIVS, "interact")
MTCONF_SET_SIMPLE(PLAYER_TRANSFER_DISTANCE, "0")
MTCONF_SET_SIMPLE(ENABLE_PVP, "true")
MTCONF_SET_SIMPLE(DISALLOW_EMPTY_PASSWORD, "false")
MTCONF_SET_SIMPLE(DISABLE_ANTICHEAT, "false")
MTCONF_SET_SIMPLE(ENABLE_ROLLBACK_RECORDING, "false")
#ifdef NDEBUG
MTCONF_SET_SIMPLE(DEPRECATED_LUA_API_HANDLING, "legacy")
#else
MTCONF_SET_SIMPLE(DEPRECATED_LUA_API_HANDLING, "log")
#endif

MTCONF_SET_SIMPLE(PROFILER_PRINT_INTERVAL, "0")
MTCONF_SET_SIMPLE(ENABLE_MAPGEN_DEBUG_INFO, "false")
MTCONF_SET_SIMPLE(ACTIVE_OBJECT_SEND_RANGE_BLOCKS, "3")
MTCONF_SET_SIMPLE(ACTIVE_BLOCK_RANGE, "2")
//MTCONF_SET_SIMPLE(MAX_SIMULTANEOUS_BLOCK_SENDS_PER_CLIENT, "1")
// This causes frametime jitter on client side, or does it?
MTCONF_SET_SIMPLE(MAX_SIMULTANEOUS_BLOCK_SENDS_PER_CLIENT, "10")
MTCONF_SET_SIMPLE(MAX_SIMULTANEOUS_BLOCK_SENDS_SERVER_TOTAL, "40")
MTCONF_SET_SIMPLE(MAX_BLOCK_SEND_DISTANCE, "9")
MTCONF_SET_SIMPLE(MAX_BLOCK_GENERATE_DISTANCE, "7")
MTCONF_SET_SIMPLE(MAX_CLEAROBJECTS_EXTRA_LOADED_BLOCKS, "4096")
MTCONF_SET_SIMPLE(TIME_SEND_INTERVAL, "5")
MTCONF_SET_SIMPLE(TIME_SPEED, "72")
MTCONF_SET_SIMPLE(YEAR_DAYS, "30")
MTCONF_SET_SIMPLE(SERVER_UNLOAD_UNUSED_DATA_TIMEOUT, "29")
MTCONF_SET_SIMPLE(MAX_OBJECTS_PER_BLOCK, "49")
MTCONF_SET_SIMPLE(SERVER_MAP_SAVE_INTERVAL, "5.3")
MTCONF_SET_SIMPLE(SQLITE_SYNCHRONOUS, "2")
MTCONF_SET_SIMPLE(FULL_BLOCK_SEND_ENABLE_MIN_TIME_FROM_BUILDING, "2.0")
MTCONF_SET_SIMPLE(DEDICATED_SERVER_STEP, "0.1")
MTCONF_SET_SIMPLE(IGNORE_WORLD_LOAD_ERRORS, "false")
MTCONF_SET_SIMPLE(REMOTE_MEDIA, "")
MTCONF_SET_SIMPLE(DEBUG_LOG_LEVEL, "2")
MTCONF_SET_SIMPLE(EMERGEQUEUE_LIMIT_TOTAL, "256")
MTCONF_SET_SIMPLE(EMERGEQUEUE_LIMIT_DISKONLY, "32")
MTCONF_SET_SIMPLE(EMERGEQUEUE_LIMIT_GENERATE, "32")
MTCONF_SET_SIMPLE(NUM_EMERGE_THREADS, "1")

// physics stuff
MTCONF_SET_SIMPLE(MOVEMENT_ACCELERATION_DEFAULT, "3")
MTCONF_SET_SIMPLE(MOVEMENT_ACCELERATION_AIR, "2")
MTCONF_SET_SIMPLE(MOVEMENT_ACCELERATION_FAST, "10")
MTCONF_SET_SIMPLE(MOVEMENT_SPEED_WALK, "4")
MTCONF_SET_SIMPLE(MOVEMENT_SPEED_CROUCH, "1.35")
MTCONF_SET_SIMPLE(MOVEMENT_SPEED_FAST, "20")
MTCONF_SET_SIMPLE(MOVEMENT_SPEED_CLIMB, "2")
MTCONF_SET_SIMPLE(MOVEMENT_SPEED_JUMP, "6.5")
MTCONF_SET_SIMPLE(MOVEMENT_LIQUID_FLUIDITY, "1")
MTCONF_SET_SIMPLE(MOVEMENT_LIQUID_FLUIDITY_SMOOTH, "0.5")
MTCONF_SET_SIMPLE(MOVEMENT_LIQUID_SINK, "10")
MTCONF_SET_SIMPLE(MOVEMENT_GRAVITY, "9.81")

//liquid stuff
MTCONF_SET_SIMPLE(LIQUID_LOOP_MAX, "100000")
MTCONF_SET_SIMPLE(LIQUID_QUEUE_PURGE_TIME, "0")
MTCONF_SET_SIMPLE(LIQUID_UPDATE, "1.0")

//mapgen stuff
MTCONF_SET_SIMPLE(MG_NAME, "v6")
MTCONF_SET_SIMPLE(WATER_LEVEL, "1")
MTCONF_SET_SIMPLE(CHUNKSIZE, "5")
MTCONF_SET_SIMPLE(MG_FLAGS, "dungeons")
MTCONF_SET_SIMPLE(MGV6_SPFLAGS, "jungles")
MTCONF_SET_SIMPLE(ENABLE_FLOATING_DUNGEONS, "true")

// IPv6
MTCONF_SET_SIMPLE(ENABLE_IPV6, "true")
MTCONF_SET_SIMPLE(IPV6_SERVER, "false")

MTCONF_SET_SIMPLE(MAIN_MENU_PATH, "")
MTCONF_SET_SIMPLE(MAIN_MENU_MOD_MGR, "1")
MTCONF_SET_SIMPLE(MAIN_MENU_GAME_MGR, "0")
MTCONF_SET_SIMPLE(MODSTORE_DOWNLOAD_URL, "https://forum.minetest.net/media/")
MTCONF_SET_SIMPLE(MODSTORE_LISTMODS_URL, "https://forum.minetest.net/mmdb/mods/")
MTCONF_SET_SIMPLE(MODSTORE_DETAILS_URL, "https://forum.minetest.net/mmdb/mod/*/")

MTCONF_SET_SIMPLE(HIGH_PRECISION_FPU, "true")

MTCONF_SET_SIMPLE(LANGUAGE, "")

#ifdef __ANDROID__
MTCONF_SET_SIMPLE(TOUCHTARGET, "true")
MTCONF_SET_EXT(TMPFOLDER, "TMPFolder", "/sdcard/" PROJECT_NAME_C "/tmp/")
MTCONF_SET_SIMPLE(TOUCHSCREEN_THRESHOLD, "20")
MTCONF_SET_SIMPLE(INVENTORY_IMAGE_HACK, "false")
#else
MTCONF_SET_SIMPLE(SCREEN_DPI, "72")
#endif

#undef MTCONF_SET_SIMPLE
