// This file is automatically generated

#pragma once
#include "settings_static.h"

inline namespace setting_type {

enum class JoystickType {
	Auto,
	Generic,
	Xbox,
};

enum class LeavesStyle {
	Fancy,
	Simple,
	Opaque,
};

enum class NodeHighlighting {
	Box,
	Halo,
	None,
};

enum class VideoDriver {
	Null,
	Software,
	Burningsvideo,
	Direct3d8,
	Direct3d9,
	Opengl,
	Ogles1,
	Ogles2,
};

enum class _3dMode {
	None,
	Anaglyph,
	Interlaced,
	Topbottom,
	Sidebyside,
	Pageflip,
};

enum class WorldAlignedMode {
	Disable,
	Enable,
	ForceSolid,
	ForceNodebox,
};

enum class AutoscaleMode {
	Disable,
	Enable,
	Force,
};

enum class ScreenshotFormat {
	Png,
	Jpg,
	Bmp,
	Pcx,
	Ppm,
	Tga,
};

enum class DeprecatedLuaApiHandling {
	Legacy,
	Log,
	Error,
};

enum class ProfilerDefaultReportFormat {
	Txt,
	Csv,
	Lua,
	Json,
	JsonPretty,
};

enum class Language {
	_,
	Be,
	Ca,
	Cs,
	Da,
	De,
	Dv,
	En,
	Eo,
	Es,
	Et,
	Fr,
	He,
	Hu,
	Id,
	It,
	Ja,
	Jbo,
	Ko,
	Ky,
	Lt,
	Ms,
	Nb,
	Nl,
	Pl,
	Pt,
	PtBR,
	Ro,
	Ru,
	Sl,
	SrCyrl,
	Sv,
	Sw,
	Tr,
	Uk,
	ZhCN,
	ZhTW,
};

enum class DebugLogLevel {
	_,
	None,
	Error,
	Warning,
	Action,
	Info,
	Verbose,
};

enum class LogColor {
	Yes,
	Detect,
	No,
};

enum class MgName {
	V5,
	V6,
	V7,
	Flat,
	Valleys,
	Fractal,
	Singlenode,
};

}

struct BuiltinSettings {

/*
 * Controls
 */
	SettingValue<bool> enable_build_where_you_stand{false};
	SettingValue<bool> free_move{false};
	SettingValue<bool> fast_move{false};
	SettingValue<bool> noclip{false};
	SettingValue<bool> cinematic{false};
	SettingValue<float> camera_smoothing{0.0};
	SettingValue<float> cinematic_camera_smoothing{0.7};
	SettingValue<bool> invert_mouse{false};
	SettingValue<float> mouse_sensitivity{0.2};
	SettingValue<bool> aux1_descends{false};
	SettingValue<bool> doubletap_jump{false};
	SettingValue<bool> always_fly_fast{true};
	SettingValue<float> repeat_rightclick_time{0.25};
	SettingValue<bool> safe_dig_and_place{false};
	SettingValue<bool> random_input{false};
	SettingValue<bool> continuous_forward{false};
	SettingValue<bool> enable_joysticks{false};
	SettingValue<int> joystick_id{0};
	SettingValue<JoystickType> joystick_type{JoystickType::Auto};
	SettingValue<float> repeat_joystick_button_time{0.17};
	SettingValue<float> joystick_frustum_sensitivity{170};

/*
 * Graphics
 */

/* In-Game */

/** Basic */
	SettingValue<bool> enable_vbo{true};
	SettingValue<bool> enable_fog{true};
	SettingValue<LeavesStyle> leaves_style{LeavesStyle::Fancy};
	SettingValue<bool> connected_glass{false};
	SettingValue<bool> smooth_lighting{true};
	SettingValue<bool> enable_clouds{true};
	SettingValue<bool> enable_3d_clouds{true};
	SettingValue<NodeHighlighting> node_highlighting{NodeHighlighting::Box};
	SettingValue<bool> enable_particles{true};

/** Filtering */
	SettingValue<bool> mip_map{false};
	SettingValue<bool> anisotropic_filter{false};
	SettingValue<bool> bilinear_filter{false};
	SettingValue<bool> trilinear_filter{false};
	SettingValue<bool> texture_clean_transparent{false};
	SettingValue<int> texture_min_size{64};
	SettingValue<int> fsaa{0};
	SettingValue<int> undersampling{0};

/** Shaders */
	SettingValue<bool> enable_shaders{true};

/*** Tone Mapping */
	SettingValue<bool> tone_mapping{false};

/*** Bumpmapping */
	SettingValue<bool> enable_bumpmapping{false};
	SettingValue<bool> generate_normalmaps{false};
	SettingValue<float> normalmaps_strength{0.6};
	SettingValue<int> normalmaps_smooth{0};

/*** Parallax Occlusion */
	SettingValue<bool> enable_parallax_occlusion{false};
	SettingValue<int> parallax_occlusion_mode{1};
	SettingValue<float> _3d_paralax_strength{0.025};
	SettingValue<int> parallax_occlusion_iterations{4};
	SettingValue<float> parallax_occlusion_scale{0.08};
	SettingValue<float> parallax_occlusion_bias{0.04};

/*** Waving Nodes */
	SettingValue<bool> enable_waving_water{false};
	SettingValue<float> water_wave_height{1.0};
	SettingValue<float> water_wave_length{20.0};
	SettingValue<float> water_wave_speed{5.0};
	SettingValue<bool> enable_waving_leaves{false};
	SettingValue<bool> enable_waving_plants{false};

/** Advanced */
	SettingValue<bool> arm_inertia{true};
	SettingValue<int> fps_max{60};
	SettingValue<int> pause_fps_max{20};
	SettingValue<bool> pause_on_lost_focus{false};
	SettingValue<int> viewing_range{100};
	SettingValue<float> near_plane{0.1};
	SettingValue<int> screen_w{1024};
	SettingValue<int> screen_h{600};
	SettingValue<bool> autosave_screensize{true};
	SettingValue<bool> fullscreen{false};
	SettingValue<int> fullscreen_bpp{24};
	SettingValue<bool> vsync{false};
	SettingValue<int> fov{72};
	SettingValue<float> display_gamma{1.0};
	SettingValue<float> lighting_alpha{0.0};
	SettingValue<float> lighting_beta{1.5};
	SettingValue<float> lighting_boost{0.2};
	SettingValue<float> lighting_boost_center{0.5};
	SettingValue<float> lighting_boost_spread{0.2};
	SettingValue<VideoDriver> video_driver{VideoDriver::Opengl};
	SettingValue<int> cloud_radius{12};
	SettingValue<float> view_bobbing_amount{1.0};
	SettingValue<float> fall_bobbing_amount{0.0};
	SettingValue<_3dMode> _3d_mode{_3dMode::None};
	SettingValue<float> console_height{0.6};
	SettingValue<int> console_alpha{200};
	SettingValue<int> formspec_fullscreen_bg_opacity{140};
	SettingValue<int> formspec_default_bg_opacity{140};
	SettingValue<int> selectionbox_width{2};
	SettingValue<int> crosshair_alpha{255};
	SettingValue<int> recent_chat_messages{6};
	SettingValue<bool> desynchronize_mapblock_texture_animation{true};
	SettingValue<float> hud_hotbar_max_width{1.0};
	SettingValue<float> hud_scaling{1.0};
	SettingValue<bool> enable_mesh_cache{false};
	SettingValue<int> mesh_generation_interval{0};
	SettingValue<int> meshgen_block_cache_size{20};
	SettingValue<bool> enable_minimap{true};
	SettingValue<bool> minimap_shape_round{true};
	SettingValue<bool> minimap_double_scan_height{true};
	SettingValue<bool> directional_colored_fog{true};
	SettingValue<float> ambient_occlusion_gamma{2.2};
	SettingValue<bool> inventory_items_animations{false};
	SettingValue<bool> inventory_image_hack{false};
	SettingValue<float> fog_start{0.4};
	SettingValue<bool> opaque_water{false};
	SettingValue<WorldAlignedMode> world_aligned_mode{WorldAlignedMode::Enable};
	SettingValue<AutoscaleMode> autoscale_mode{AutoscaleMode::Disable};
	SettingValue<bool> show_entity_selectionbox{true};

/* Menus */
	SettingValue<bool> menu_clouds{true};
	SettingValue<float> gui_scaling{1.0};
	SettingValue<bool> gui_scaling_filter{false};
	SettingValue<bool> gui_scaling_filter_txr2img{true};
	SettingValue<int> tooltip_show_delay{400};
	SettingValue<bool> tooltip_append_itemname{false};
	SettingValue<bool> freetype{true};
	SettingValue<int> font_size{16};
	SettingValue<int> font_shadow{1};
	SettingValue<int> font_shadow_alpha{127};
	SettingValue<int> mono_font_size{15};
	SettingValue<int> fallback_font_size{15};
	SettingValue<int> fallback_font_shadow{1};
	SettingValue<int> fallback_font_shadow_alpha{128};
	SettingValue<ScreenshotFormat> screenshot_format{ScreenshotFormat::Png};
	SettingValue<int> screenshot_quality{0};

/* Advanced */
	SettingValue<int> screen_dpi{72};
	SettingValue<bool> enable_console{false};

/*
 * Sound
 */
	SettingValue<bool> enable_sound{true};
	SettingValue<float> sound_volume{0.7};
	SettingValue<bool> mute_sound{false};

/*
 * Client
 */

/* Network */
	SettingValue<int> remote_port{30000};
	SettingValue<bool> enable_local_map_saving{false};
	SettingValue<bool> enable_remote_media_server{true};
	SettingValue<bool> enable_client_modding{false};
	SettingValue<int> max_out_chat_queue_size{20};

/* Advanced */
	SettingValue<int> client_unload_unused_data_timeout{600};
	SettingValue<int> client_mapblock_limit{5000};
	SettingValue<bool> show_debug{false};

/*
 * Server / Singleplayer
 */
	SettingValue<bool> server_announce{false};
	SettingValue<bool> strip_color_codes{false};

/* Network */
	SettingValue<int> port{30000};
	SettingValue<bool> strict_protocol_version_checking{false};
	SettingValue<bool> ipv6_server{false};

/** Advanced */
	SettingValue<int> max_simultaneous_block_sends_per_client{10};
	SettingValue<float> full_block_send_enable_min_time_from_building{2.0};
	SettingValue<int> max_packets_per_iteration{1024};

/* Game */
	SettingValue<int> max_users{15};
	SettingValue<int> item_entity_ttl{900};
	SettingValue<bool> show_statusline_on_connect{true};
	SettingValue<bool> enable_damage{false};
	SettingValue<bool> creative_mode{false};
	SettingValue<bool> unlimited_player_transfer_distance{true};
	SettingValue<int> player_transfer_distance{0};
	SettingValue<bool> enable_pvp{true};
	SettingValue<bool> enable_mod_channels{false};
	SettingValue<bool> disallow_empty_password{false};
	SettingValue<bool> disable_anticheat{false};
	SettingValue<bool> enable_rollback_recording{false};
	SettingValue<bool> ask_reconnect_on_crash{false};
	SettingValue<int> active_object_send_range_blocks{3};
	SettingValue<int> active_block_range{3};
	SettingValue<int> max_block_send_distance{9};
	SettingValue<int> max_forceloaded_blocks{16};
	SettingValue<int> time_send_interval{5};
	SettingValue<int> time_speed{72};
	SettingValue<int> world_start_time{5250};
	SettingValue<float> server_map_save_interval{5.3};

/** Physics */
	SettingValue<float> movement_acceleration_default{3};
	SettingValue<float> movement_acceleration_air{2};
	SettingValue<float> movement_acceleration_fast{10};
	SettingValue<float> movement_speed_walk{4};
	SettingValue<float> movement_speed_crouch{1.35};
	SettingValue<float> movement_speed_fast{20};
	SettingValue<float> movement_speed_climb{3};
	SettingValue<float> movement_speed_jump{6.5};
	SettingValue<float> movement_liquid_fluidity{1};
	SettingValue<float> movement_liquid_fluidity_smooth{0.5};
	SettingValue<float> movement_liquid_sink{10};
	SettingValue<float> movement_gravity{9.81};

/** Advanced */
	SettingValue<DeprecatedLuaApiHandling> deprecated_lua_api_handling{DeprecatedLuaApiHandling::Legacy};
	SettingValue<int> max_clearobjects_extra_loaded_blocks{4096};
	SettingValue<int> server_unload_unused_data_timeout{29};
	SettingValue<int> max_objects_per_block{64};
	SettingValue<int> sqlite_synchronous{2};
	SettingValue<float> dedicated_server_step{0.09};
	SettingValue<float> active_block_mgmt_interval{2.0};
	SettingValue<float> abm_interval{1.0};
	SettingValue<float> nodetimer_interval{0.2};
	SettingValue<bool> ignore_world_load_errors{false};
	SettingValue<int> liquid_loop_max{100000};
	SettingValue<int> liquid_queue_purge_time{0};
	SettingValue<float> liquid_update{1.0};
	SettingValue<int> block_send_optimize_distance{4};
	SettingValue<bool> server_side_occlusion_culling{true};
	SettingValue<int> csm_flavour_limits{18};
	SettingValue<int> csm_flavour_noderange_limit{8};

/* Security */
	SettingValue<bool> secure_enable_security{true};

/* Advanced */

/** Profiling */
	SettingValue<bool> profiler_load{false};
	SettingValue<ProfilerDefaultReportFormat> profiler_default_report_format{ProfilerDefaultReportFormat::Txt};

/*** Instrumentation */
	SettingValue<bool> instrument_entity{true};
	SettingValue<bool> instrument_abm{true};
	SettingValue<bool> instrument_lbm{true};
	SettingValue<bool> instrument_chatcommand{true};
	SettingValue<bool> instrument_global_callback{true};

/**** Advanced */
	SettingValue<bool> instrument_builtin{false};
	SettingValue<bool> instrument_profiler{false};

/*
 * Client and Server
 */
	SettingValue<Language> language{Language::_};
	SettingValue<DebugLogLevel> debug_log_level{DebugLogLevel::Action};
	SettingValue<LogColor> log_color{LogColor::Detect};
	SettingValue<bool> enable_ipv6{true};

/* Advanced */
	SettingValue<int> curl_timeout{5000};
	SettingValue<int> curl_parallel_limit{8};
	SettingValue<int> curl_file_download_timeout{300000};
	SettingValue<bool> high_precision_fpu{true};
	SettingValue<int> main_menu_game_mgr{0};
	SettingValue<int> main_menu_mod_mgr{1};
	SettingValue<int> profiler_print_interval{0};

/*
 * Mapgen
 */
	SettingValue<MgName> mg_name{MgName::V7};
	SettingValue<int> water_level{1};
	SettingValue<int> max_block_generate_distance{6};
	SettingValue<int> mapgen_limit{31000};
	SettingValue<bool> projecting_dungeons{true};

/* Biome API temperature and humidity noise parameters */

/* Mapgen V5 */
	SettingValue<float> mgv5_cave_width{0.125};
	SettingValue<int> mgv5_large_cave_depth{-256};
	SettingValue<int> mgv5_lava_depth{-256};
	SettingValue<int> mgv5_cavern_limit{-256};
	SettingValue<int> mgv5_cavern_taper{256};
	SettingValue<float> mgv5_cavern_threshold{0.7};

/** Noises */

/* Mapgen V6 */
	SettingValue<float> mgv6_freq_desert{0.45};
	SettingValue<float> mgv6_freq_beach{0.15};

/** Noises */

/* Mapgen V7 */
	SettingValue<int> mgv7_mount_zero_level{0};
	SettingValue<float> mgv7_cave_width{0.09};
	SettingValue<int> mgv7_large_cave_depth{-33};
	SettingValue<int> mgv7_lava_depth{-256};
	SettingValue<float> mgv7_float_mount_density{0.6};
	SettingValue<float> mgv7_float_mount_height{128.0};
	SettingValue<float> mgv7_float_mount_exponent{0.75};
	SettingValue<int> mgv7_floatland_level{1280};
	SettingValue<int> mgv7_shadow_limit{1024};
	SettingValue<int> mgv7_cavern_limit{-256};
	SettingValue<int> mgv7_cavern_taper{256};
	SettingValue<float> mgv7_cavern_threshold{0.7};

/** Noises */

/* Mapgen Carpathian */
	SettingValue<float> mgcarpathian_cave_width{0.09};
	SettingValue<int> mgcarpathian_large_cave_depth{-33};
	SettingValue<int> mgcarpathian_lava_depth{-256};
	SettingValue<int> mgcarpathian_cavern_limit{-256};
	SettingValue<int> mgcarpathian_cavern_taper{256};
	SettingValue<float> mgcarpathian_cavern_threshold{0.7};

/** Noises */

/* Mapgen Flat */
	SettingValue<int> mgflat_ground_level{8};
	SettingValue<int> mgflat_large_cave_depth{-33};
	SettingValue<int> mgflat_lava_depth{-256};
	SettingValue<float> mgflat_cave_width{0.09};
	SettingValue<float> mgflat_lake_threshold{-0.45};
	SettingValue<float> mgflat_lake_steepness{48.0};
	SettingValue<float> mgflat_hill_threshold{0.45};
	SettingValue<float> mgflat_hill_steepness{64.0};

/** Noises */

/* Mapgen Fractal */
	SettingValue<float> mgfractal_cave_width{0.09};
	SettingValue<int> mgfractal_large_cave_depth{-33};
	SettingValue<int> mgfractal_lava_depth{-256};
	SettingValue<int> mgfractal_fractal{1};
	SettingValue<int> mgfractal_iterations{11};
	SettingValue<float> mgfractal_slice_w{0.0};
	SettingValue<float> mgfractal_julia_x{0.33};
	SettingValue<float> mgfractal_julia_y{0.33};
	SettingValue<float> mgfractal_julia_z{0.33};
	SettingValue<float> mgfractal_julia_w{0.33};

/** Noises */

/* Mapgen Valleys */
	SettingValue<int> mgvalleys_altitude_chill{90};
	SettingValue<int> mgvalleys_large_cave_depth{-33};
	SettingValue<int> mgvalleys_lava_features{0};
	SettingValue<int> mgvalleys_massive_cave_depth{-256};
	SettingValue<int> mgvalleys_river_depth{4};
	SettingValue<int> mgvalleys_river_size{5};
	SettingValue<int> mgvalleys_water_features{0};
	SettingValue<float> mgvalleys_cave_width{0.09};

/** Noises */

/* Advanced */
	SettingValue<int> chunksize{5};
	SettingValue<bool> enable_mapgen_debug_info{false};
	SettingValue<int> emergequeue_limit_total{256};
	SettingValue<int> emergequeue_limit_diskonly{32};
	SettingValue<int> emergequeue_limit_generate{32};
	SettingValue<int> num_emerge_threads{1};

};

extern const BuiltinSettings &builtin_settings;
extern StaticSettingsManager builtin_settings_manager;
